name: FailedChecker

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/skylab-devs/cosmic:squashed

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-print flake8-quotes
    - name: Check for showstoppers
      run: |
        # stop the build if there are Python syntax errors
        flake8 . --count --select=E999 --show-source --statistics

  shellcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check for install script errors
      uses: ludeeus/action-shellcheck@0.1.0
